// Your photos are loaded in the order below. Add or remove entries as needed.
// All src paths point at the optimised WebP copies in photos/optimized/.
// To add a new photo: drop the original in photos/, run photos/optimize.sh, then add an entry below.
window.ANNIVERSARY_PHOTOS = [
  { src: 'photos/optimized/CarPhoto.webp', caption: '2 sweet bubbas in love ♡', alt: 'Deepit and Nishtha smiling beside a car' },
  { src: 'photos/optimized/IMG20260729122902.webp', caption: '2 sweet bubbas in love ♡', alt: 'Deepit and Nishtha together overlooking a city' },
  { src: 'photos/optimized/IMG_0545.webp', caption: '2 sweet bubbas in love ♡', alt: 'Deepit and Nishtha sharing a moment together' },
  { src: 'photos/optimized/IMG20260801150927_01.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20260802-WA0077.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20260803-WA0076.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_0087.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_0122.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_8396.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_6866.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_4306.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_4020_1.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG20250414141029.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250401-WA0001.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250401-WA0003.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250330-WA0058.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250330-WA0059.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250330-WA0061.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250330-WA0063.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250330-WA0069.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG_20250330_113114.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0060.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0061.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0063.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0067.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0069.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0070.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0071.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/IMG-20250326-WA0072.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' },
  { src: 'photos/optimized/35883d1e-5b2a-4f2f-9a35-33e95fbf0483.webp', caption: '2 sweet bubbas in love ♡', alt: 'A photograph from our time together' }
];
